services:
  gohole:
    image: specialfish9/gohole:latest
    links:
      - clickhouse
    ports:
      - "8080:8080/tcp"
      - "8053:53/udp"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./gohole.yaml:/gohole.yaml
      - ./block.txt:/block.txt
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_USER=gohole
      - CLICKHOUSE_PASSWORD=password
    volumes:
      - ./clickhouse-vol/data:/var/lib/clickhouse
      - ./clickhouse-vol/logs:/var/log/clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
