services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gohole
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gohole
    volumes:
      - ./postgres-vol:/var/lib/postgresql
