// Code generated by MockGen. DO NOT EDIT.
// Source: gohole/internal/filter (interfaces: Filter)
//
// Generated by this command:
//
//	mockgen -destination=../mock/filter/filter.go -typed -package mockfilter gohole/internal/filter Filter
//

// Package mockfilter is a generated GoMock package.
package mockfilter

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFilter is a mock of Filter interface.
type MockFilter struct {
	ctrl     *gomock.Controller
	recorder *MockFilterMockRecorder
	isgomock struct{}
}

// MockFilterMockRecorder is the mock recorder for MockFilter.
type MockFilterMockRecorder struct {
	mock *MockFilter
}

// NewMockFilter creates a new mock instance.
func NewMockFilter(ctrl *gomock.Controller) *MockFilter {
	mock := &MockFilter{ctrl: ctrl}
	mock.recorder = &MockFilterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilter) EXPECT() *MockFilterMockRecorder {
	return m.recorder
}

// Filter mocks base method.
func (m *MockFilter) Filter(q string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filter", q)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Filter indicates an expected call of Filter.
func (mr *MockFilterMockRecorder) Filter(q any) *MockFilterFilterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*MockFilter)(nil).Filter), q)
	return &MockFilterFilterCall{Call: call}
}

// MockFilterFilterCall wrap *gomock.Call
type MockFilterFilterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFilterFilterCall) Return(arg0 bool, arg1 error) *MockFilterFilterCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFilterFilterCall) Do(f func(string) (bool, error)) *MockFilterFilterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFilterFilterCall) DoAndReturn(f func(string) (bool, error)) *MockFilterFilterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Size mocks base method.
func (m *MockFilter) Size() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Size")
	ret0, _ := ret[0].(int)
	return ret0
}

// Size indicates an expected call of Size.
func (mr *MockFilterMockRecorder) Size() *MockFilterSizeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Size", reflect.TypeOf((*MockFilter)(nil).Size))
	return &MockFilterSizeCall{Call: call}
}

// MockFilterSizeCall wrap *gomock.Call
type MockFilterSizeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFilterSizeCall) Return(arg0 int) *MockFilterSizeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFilterSizeCall) Do(f func() int) *MockFilterSizeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFilterSizeCall) DoAndReturn(f func() int) *MockFilterSizeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
