// Code generated by MockGen. DO NOT EDIT.
// Source: queryservice.go
//
// Generated by this command:
//
//	mockgen -destination=../mock/query/queryservice.go -typed -source=queryservice.go
//

// Package mock_query is a generated GoMock package.
package mock_query

import (
	context "context"
	database "gohole/internal/database"
	query "gohole/internal/query"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockService) GetAll(ctx context.Context, limit int, name string) ([]database.Query, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, limit, name)
	ret0, _ := ret[0].([]database.Query)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockServiceMockRecorder) GetAll(ctx, limit, name any) *MockServiceGetAllCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockService)(nil).GetAll), ctx, limit, name)
	return &MockServiceGetAllCall{Call: call}
}

// MockServiceGetAllCall wrap *gomock.Call
type MockServiceGetAllCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceGetAllCall) Return(arg0 []database.Query, arg1 error) *MockServiceGetAllCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceGetAllCall) Do(f func(context.Context, int, string) ([]database.Query, error)) *MockServiceGetAllCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceGetAllCall) DoAndReturn(f func(context.Context, int, string) ([]database.Query, error)) *MockServiceGetAllCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetBlockListStats mocks base method.
func (m *MockService) GetBlockListStats() (*query.BlockListStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockListStats")
	ret0, _ := ret[0].(*query.BlockListStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockListStats indicates an expected call of GetBlockListStats.
func (mr *MockServiceMockRecorder) GetBlockListStats() *MockServiceGetBlockListStatsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockListStats", reflect.TypeOf((*MockService)(nil).GetBlockListStats))
	return &MockServiceGetBlockListStatsCall{Call: call}
}

// MockServiceGetBlockListStatsCall wrap *gomock.Call
type MockServiceGetBlockListStatsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceGetBlockListStatsCall) Return(arg0 *query.BlockListStats, arg1 error) *MockServiceGetBlockListStatsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceGetBlockListStatsCall) Do(f func() (*query.BlockListStats, error)) *MockServiceGetBlockListStatsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceGetBlockListStatsCall) DoAndReturn(f func() (*query.BlockListStats, error)) *MockServiceGetBlockListStatsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetDomainDetails mocks base method.
func (m *MockService) GetDomainDetails(ctx context.Context, name string, interval query.Interval, granularity query.Granularity) (*query.DomainDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDomainDetails", ctx, name, interval, granularity)
	ret0, _ := ret[0].(*query.DomainDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDomainDetails indicates an expected call of GetDomainDetails.
func (mr *MockServiceMockRecorder) GetDomainDetails(ctx, name, interval, granularity any) *MockServiceGetDomainDetailsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDomainDetails", reflect.TypeOf((*MockService)(nil).GetDomainDetails), ctx, name, interval, granularity)
	return &MockServiceGetDomainDetailsCall{Call: call}
}

// MockServiceGetDomainDetailsCall wrap *gomock.Call
type MockServiceGetDomainDetailsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceGetDomainDetailsCall) Return(arg0 *query.DomainDetail, arg1 error) *MockServiceGetDomainDetailsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceGetDomainDetailsCall) Do(f func(context.Context, string, query.Interval, query.Granularity) (*query.DomainDetail, error)) *MockServiceGetDomainDetailsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceGetDomainDetailsCall) DoAndReturn(f func(context.Context, string, query.Interval, query.Granularity) (*query.DomainDetail, error)) *MockServiceGetDomainDetailsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetDomainStats mocks base method.
func (m *MockService) GetDomainStats(ctx context.Context, interval query.Interval) (query.DomainStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDomainStats", ctx, interval)
	ret0, _ := ret[0].(query.DomainStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDomainStats indicates an expected call of GetDomainStats.
func (mr *MockServiceMockRecorder) GetDomainStats(ctx, interval any) *MockServiceGetDomainStatsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDomainStats", reflect.TypeOf((*MockService)(nil).GetDomainStats), ctx, interval)
	return &MockServiceGetDomainStatsCall{Call: call}
}

// MockServiceGetDomainStatsCall wrap *gomock.Call
type MockServiceGetDomainStatsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceGetDomainStatsCall) Return(arg0 query.DomainStats, arg1 error) *MockServiceGetDomainStatsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceGetDomainStatsCall) Do(f func(context.Context, query.Interval) (query.DomainStats, error)) *MockServiceGetDomainStatsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceGetDomainStatsCall) DoAndReturn(f func(context.Context, query.Interval) (query.DomainStats, error)) *MockServiceGetDomainStatsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetHistory mocks base method.
func (m *MockService) GetHistory(ctx context.Context, interval query.Interval, granularity query.Granularity) ([]query.QueryHistoryPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory", ctx, interval, granularity)
	ret0, _ := ret[0].([]query.QueryHistoryPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockServiceMockRecorder) GetHistory(ctx, interval, granularity any) *MockServiceGetHistoryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockService)(nil).GetHistory), ctx, interval, granularity)
	return &MockServiceGetHistoryCall{Call: call}
}

// MockServiceGetHistoryCall wrap *gomock.Call
type MockServiceGetHistoryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceGetHistoryCall) Return(arg0 []query.QueryHistoryPoint, arg1 error) *MockServiceGetHistoryCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceGetHistoryCall) Do(f func(context.Context, query.Interval, query.Granularity) ([]query.QueryHistoryPoint, error)) *MockServiceGetHistoryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceGetHistoryCall) DoAndReturn(f func(context.Context, query.Interval, query.Granularity) ([]query.QueryHistoryPoint, error)) *MockServiceGetHistoryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetHostStats mocks base method.
func (m *MockService) GetHostStats(ctx context.Context, interival query.Interval) ([]database.HostStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHostStats", ctx, interival)
	ret0, _ := ret[0].([]database.HostStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHostStats indicates an expected call of GetHostStats.
func (mr *MockServiceMockRecorder) GetHostStats(ctx, interival any) *MockServiceGetHostStatsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHostStats", reflect.TypeOf((*MockService)(nil).GetHostStats), ctx, interival)
	return &MockServiceGetHostStatsCall{Call: call}
}

// MockServiceGetHostStatsCall wrap *gomock.Call
type MockServiceGetHostStatsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceGetHostStatsCall) Return(arg0 []database.HostStat, arg1 error) *MockServiceGetHostStatsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceGetHostStatsCall) Do(f func(context.Context, query.Interval) ([]database.HostStat, error)) *MockServiceGetHostStatsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceGetHostStatsCall) DoAndReturn(f func(context.Context, query.Interval) ([]database.HostStat, error)) *MockServiceGetHostStatsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetStats mocks base method.
func (m *MockService) GetStats(ctx context.Context, interval query.Interval) (*query.Stats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx, interval)
	ret0, _ := ret[0].(*query.Stats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockServiceMockRecorder) GetStats(ctx, interval any) *MockServiceGetStatsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockService)(nil).GetStats), ctx, interval)
	return &MockServiceGetStatsCall{Call: call}
}

// MockServiceGetStatsCall wrap *gomock.Call
type MockServiceGetStatsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceGetStatsCall) Return(arg0 *query.Stats, arg1 error) *MockServiceGetStatsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceGetStatsCall) Do(f func(context.Context, query.Interval) (*query.Stats, error)) *MockServiceGetStatsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceGetStatsCall) DoAndReturn(f func(context.Context, query.Interval) (*query.Stats, error)) *MockServiceGetStatsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m *MockService) Save(ctx context.Context, q database.Query) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, q)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockServiceMockRecorder) Save(ctx, q any) *MockServiceSaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockService)(nil).Save), ctx, q)
	return &MockServiceSaveCall{Call: call}
}

// MockServiceSaveCall wrap *gomock.Call
type MockServiceSaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceSaveCall) Return(arg0 error) *MockServiceSaveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceSaveCall) Do(f func(context.Context, database.Query) error) *MockServiceSaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceSaveCall) DoAndReturn(f func(context.Context, database.Query) error) *MockServiceSaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ShouldAllow mocks base method.
func (m *MockService) ShouldAllow(name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShouldAllow", name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShouldAllow indicates an expected call of ShouldAllow.
func (mr *MockServiceMockRecorder) ShouldAllow(name any) *MockServiceShouldAllowCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShouldAllow", reflect.TypeOf((*MockService)(nil).ShouldAllow), name)
	return &MockServiceShouldAllowCall{Call: call}
}

// MockServiceShouldAllowCall wrap *gomock.Call
type MockServiceShouldAllowCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceShouldAllowCall) Return(arg0 bool, arg1 error) *MockServiceShouldAllowCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceShouldAllowCall) Do(f func(string) (bool, error)) *MockServiceShouldAllowCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceShouldAllowCall) DoAndReturn(f func(string) (bool, error)) *MockServiceShouldAllowCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
