// Code generated by MockGen. DO NOT EDIT.
// Source: gohole/internal/database (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/database/repository.go -typed -package mockrepo gohole/internal/database Repository
//

// Package mockrepo is a generated GoMock package.
package mockrepo

import (
	context "context"
	database "gohole/internal/database"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockRepository) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockRepositoryMockRecorder) Close() *MockRepositoryCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRepository)(nil).Close))
	return &MockRepositoryCloseCall{Call: call}
}

// MockRepositoryCloseCall wrap *gomock.Call
type MockRepositoryCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryCloseCall) Return(arg0 error) *MockRepositoryCloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryCloseCall) Do(f func() error) *MockRepositoryCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryCloseCall) DoAndReturn(f func() error) *MockRepositoryCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindAll mocks base method.
func (m *MockRepository) FindAll(ctx context.Context) ([]database.Query, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]database.Query)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockRepositoryMockRecorder) FindAll(ctx any) *MockRepositoryFindAllCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockRepository)(nil).FindAll), ctx)
	return &MockRepositoryFindAllCall{Call: call}
}

// MockRepositoryFindAllCall wrap *gomock.Call
type MockRepositoryFindAllCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryFindAllCall) Return(arg0 []database.Query, arg1 error) *MockRepositoryFindAllCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryFindAllCall) Do(f func(context.Context) ([]database.Query, error)) *MockRepositoryFindAllCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryFindAllCall) DoAndReturn(f func(context.Context) ([]database.Query, error)) *MockRepositoryFindAllCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindAllByInterval mocks base method.
func (m *MockRepository) FindAllByInterval(ctx context.Context, since time.Time) ([]database.Query, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByInterval", ctx, since)
	ret0, _ := ret[0].([]database.Query)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllByInterval indicates an expected call of FindAllByInterval.
func (mr *MockRepositoryMockRecorder) FindAllByInterval(ctx, since any) *MockRepositoryFindAllByIntervalCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByInterval", reflect.TypeOf((*MockRepository)(nil).FindAllByInterval), ctx, since)
	return &MockRepositoryFindAllByIntervalCall{Call: call}
}

// MockRepositoryFindAllByIntervalCall wrap *gomock.Call
type MockRepositoryFindAllByIntervalCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryFindAllByIntervalCall) Return(arg0 []database.Query, arg1 error) *MockRepositoryFindAllByIntervalCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryFindAllByIntervalCall) Do(f func(context.Context, time.Time) ([]database.Query, error)) *MockRepositoryFindAllByIntervalCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryFindAllByIntervalCall) DoAndReturn(f func(context.Context, time.Time) ([]database.Query, error)) *MockRepositoryFindAllByIntervalCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindAllLimit mocks base method.
func (m *MockRepository) FindAllLimit(ctx context.Context, limit int, name string) ([]database.Query, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllLimit", ctx, limit, name)
	ret0, _ := ret[0].([]database.Query)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllLimit indicates an expected call of FindAllLimit.
func (mr *MockRepositoryMockRecorder) FindAllLimit(ctx, limit, name any) *MockRepositoryFindAllLimitCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllLimit", reflect.TypeOf((*MockRepository)(nil).FindAllLimit), ctx, limit, name)
	return &MockRepositoryFindAllLimitCall{Call: call}
}

// MockRepositoryFindAllLimitCall wrap *gomock.Call
type MockRepositoryFindAllLimitCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryFindAllLimitCall) Return(arg0 []database.Query, arg1 error) *MockRepositoryFindAllLimitCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryFindAllLimitCall) Do(f func(context.Context, int, string) ([]database.Query, error)) *MockRepositoryFindAllLimitCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryFindAllLimitCall) DoAndReturn(f func(context.Context, int, string) ([]database.Query, error)) *MockRepositoryFindAllLimitCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindDomainDetailsPoints mocks base method.
func (m *MockRepository) FindDomainDetailsPoints(ctx context.Context, name string, since time.Time, granularity time.Duration) ([]database.Point, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDomainDetailsPoints", ctx, name, since, granularity)
	ret0, _ := ret[0].([]database.Point)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDomainDetailsPoints indicates an expected call of FindDomainDetailsPoints.
func (mr *MockRepositoryMockRecorder) FindDomainDetailsPoints(ctx, name, since, granularity any) *MockRepositoryFindDomainDetailsPointsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDomainDetailsPoints", reflect.TypeOf((*MockRepository)(nil).FindDomainDetailsPoints), ctx, name, since, granularity)
	return &MockRepositoryFindDomainDetailsPointsCall{Call: call}
}

// MockRepositoryFindDomainDetailsPointsCall wrap *gomock.Call
type MockRepositoryFindDomainDetailsPointsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryFindDomainDetailsPointsCall) Return(arg0 []database.Point, arg1 error) *MockRepositoryFindDomainDetailsPointsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryFindDomainDetailsPointsCall) Do(f func(context.Context, string, time.Time, time.Duration) ([]database.Point, error)) *MockRepositoryFindDomainDetailsPointsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryFindDomainDetailsPointsCall) DoAndReturn(f func(context.Context, string, time.Time, time.Duration) ([]database.Point, error)) *MockRepositoryFindDomainDetailsPointsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindDomainStats mocks base method.
func (m *MockRepository) FindDomainStats(ctx context.Context, since time.Time) (database.DomainStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDomainStats", ctx, since)
	ret0, _ := ret[0].(database.DomainStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDomainStats indicates an expected call of FindDomainStats.
func (mr *MockRepositoryMockRecorder) FindDomainStats(ctx, since any) *MockRepositoryFindDomainStatsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDomainStats", reflect.TypeOf((*MockRepository)(nil).FindDomainStats), ctx, since)
	return &MockRepositoryFindDomainStatsCall{Call: call}
}

// MockRepositoryFindDomainStatsCall wrap *gomock.Call
type MockRepositoryFindDomainStatsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryFindDomainStatsCall) Return(arg0 database.DomainStats, arg1 error) *MockRepositoryFindDomainStatsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryFindDomainStatsCall) Do(f func(context.Context, time.Time) (database.DomainStats, error)) *MockRepositoryFindDomainStatsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryFindDomainStatsCall) DoAndReturn(f func(context.Context, time.Time) (database.DomainStats, error)) *MockRepositoryFindDomainStatsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindHostStats mocks base method.
func (m *MockRepository) FindHostStats(ctx context.Context, since time.Time) ([]database.HostStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindHostStats", ctx, since)
	ret0, _ := ret[0].([]database.HostStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindHostStats indicates an expected call of FindHostStats.
func (mr *MockRepositoryMockRecorder) FindHostStats(ctx, since any) *MockRepositoryFindHostStatsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindHostStats", reflect.TypeOf((*MockRepository)(nil).FindHostStats), ctx, since)
	return &MockRepositoryFindHostStatsCall{Call: call}
}

// MockRepositoryFindHostStatsCall wrap *gomock.Call
type MockRepositoryFindHostStatsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryFindHostStatsCall) Return(arg0 []database.HostStat, arg1 error) *MockRepositoryFindHostStatsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryFindHostStatsCall) Do(f func(context.Context, time.Time) ([]database.HostStat, error)) *MockRepositoryFindHostStatsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryFindHostStatsCall) DoAndReturn(f func(context.Context, time.Time) ([]database.HostStat, error)) *MockRepositoryFindHostStatsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindTopDomains mocks base method.
func (m *MockRepository) FindTopDomains(ctx context.Context, blocked bool, since time.Time, limit int) ([]database.TopDomain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTopDomains", ctx, blocked, since, limit)
	ret0, _ := ret[0].([]database.TopDomain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTopDomains indicates an expected call of FindTopDomains.
func (mr *MockRepositoryMockRecorder) FindTopDomains(ctx, blocked, since, limit any) *MockRepositoryFindTopDomainsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTopDomains", reflect.TypeOf((*MockRepository)(nil).FindTopDomains), ctx, blocked, since, limit)
	return &MockRepositoryFindTopDomainsCall{Call: call}
}

// MockRepositoryFindTopDomainsCall wrap *gomock.Call
type MockRepositoryFindTopDomainsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryFindTopDomainsCall) Return(arg0 []database.TopDomain, arg1 error) *MockRepositoryFindTopDomainsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryFindTopDomainsCall) Do(f func(context.Context, bool, time.Time, int) ([]database.TopDomain, error)) *MockRepositoryFindTopDomainsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryFindTopDomainsCall) DoAndReturn(f func(context.Context, bool, time.Time, int) ([]database.TopDomain, error)) *MockRepositoryFindTopDomainsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SaveQuery mocks base method.
func (m *MockRepository) SaveQuery(ctx context.Context, q database.Query) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveQuery", ctx, q)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveQuery indicates an expected call of SaveQuery.
func (mr *MockRepositoryMockRecorder) SaveQuery(ctx, q any) *MockRepositorySaveQueryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveQuery", reflect.TypeOf((*MockRepository)(nil).SaveQuery), ctx, q)
	return &MockRepositorySaveQueryCall{Call: call}
}

// MockRepositorySaveQueryCall wrap *gomock.Call
type MockRepositorySaveQueryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositorySaveQueryCall) Return(arg0 error) *MockRepositorySaveQueryCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositorySaveQueryCall) Do(f func(context.Context, database.Query) error) *MockRepositorySaveQueryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositorySaveQueryCall) DoAndReturn(f func(context.Context, database.Query) error) *MockRepositorySaveQueryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
