{
 "title": "GOHOLE",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "name", "label": "Domain" }
  ]
 },
 "panels": [
  {
   "title": "${name} queries per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfMinute(timestamp) AS minute,\n    count() AS query_count\nFROM query\nWHERE name ilike '${name}'\nGROUP BY minute\nORDER BY minute;"
    }
   ]
  },
  {
   "title": "Most queried",
   "type": "table",
   "gridPos": { "h": 24, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select name, count(name) as count\nfrom query\ngroup by name\norder by count desc"
    }
   ]
  },
  {
   "title": "Q per H",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfHour(timestamp) AS hour,\n    count() AS query_count\nFROM query\nGROUP BY hour\nORDER BY hour;"
    }
   ]
  },
  {
   "title": "Q per M",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfMinute(timestamp) AS minute,\n    count() AS query_count\nFROM query\nWHERE host regexp '^192\\.168\\.0\\.1[1-9]$'\nGROUP BY minute\nORDER BY minute;"
    }
   ]
  },
  {
   "title": "Query MS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT timestamp as \"time\", millis FROM \"default\".\"query\" WHERE ( time >= $__fromTime AND time <= $__toTime ) ORDER BY time ASC LIMIT 1000000"
    }
   ]
  }
 ]
}