// Code generated by MockGen. DO NOT EDIT.
// Source: cache.go
//
// Generated by this command:
//
//	mockgen -destination=../../mock/dns/cache.go -typed -source=cache.go
//

// Package mock_dns is a generated GoMock package.
package mock_dns

import (
	dns0 "gohole/internal/controller/dns"
	reflect "reflect"

	dns "codeberg.org/miekg/dns"
	gomock "go.uber.org/mock/gomock"
)

// MockCache is a mock of Cache interface.
type MockCache struct {
	ctrl     *gomock.Controller
	recorder *MockCacheMockRecorder
	isgomock struct{}
}

// MockCacheMockRecorder is the mock recorder for MockCache.
type MockCacheMockRecorder struct {
	mock *MockCache
}

// NewMockCache creates a new mock instance.
func NewMockCache(ctrl *gomock.Controller) *MockCache {
	mock := &MockCache{ctrl: ctrl}
	mock.recorder = &MockCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCache) EXPECT() *MockCacheMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockCache) Get(key dns0.CacheKey) (bool, []dns.RR, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].([]dns.RR)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockCacheMockRecorder) Get(key any) *MockCacheGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCache)(nil).Get), key)
	return &MockCacheGetCall{Call: call}
}

// MockCacheGetCall wrap *gomock.Call
type MockCacheGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCacheGetCall) Return(arg0 bool, arg1 []dns.RR, arg2 bool) *MockCacheGetCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCacheGetCall) Do(f func(dns0.CacheKey) (bool, []dns.RR, bool)) *MockCacheGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCacheGetCall) DoAndReturn(f func(dns0.CacheKey) (bool, []dns.RR, bool)) *MockCacheGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Set mocks base method.
func (m *MockCache) Set(key dns0.CacheKey, answer []dns.RR, ttl uint32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", key, answer, ttl)
}

// Set indicates an expected call of Set.
func (mr *MockCacheMockRecorder) Set(key, answer, ttl any) *MockCacheSetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCache)(nil).Set), key, answer, ttl)
	return &MockCacheSetCall{Call: call}
}

// MockCacheSetCall wrap *gomock.Call
type MockCacheSetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCacheSetCall) Return() *MockCacheSetCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCacheSetCall) Do(f func(dns0.CacheKey, []dns.RR, uint32)) *MockCacheSetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCacheSetCall) DoAndReturn(f func(dns0.CacheKey, []dns.RR, uint32)) *MockCacheSetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetBlocked mocks base method.
func (m *MockCache) SetBlocked(key dns0.CacheKey) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetBlocked", key)
}

// SetBlocked indicates an expected call of SetBlocked.
func (mr *MockCacheMockRecorder) SetBlocked(key any) *MockCacheSetBlockedCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBlocked", reflect.TypeOf((*MockCache)(nil).SetBlocked), key)
	return &MockCacheSetBlockedCall{Call: call}
}

// MockCacheSetBlockedCall wrap *gomock.Call
type MockCacheSetBlockedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCacheSetBlockedCall) Return() *MockCacheSetBlockedCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCacheSetBlockedCall) Do(f func(dns0.CacheKey)) *MockCacheSetBlockedCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCacheSetBlockedCall) DoAndReturn(f func(dns0.CacheKey)) *MockCacheSetBlockedCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
