// Code generated by MockGen. DO NOT EDIT.
// Source: dns.go
//
// Generated by this command:
//
//	mockgen -destination=../../mock/dns/dnsclient.go -typed -source=dns.go
//

// Package mock_dns is a generated GoMock package.
package mock_dns

import (
	context "context"
	reflect "reflect"
	time "time"

	dns "codeberg.org/miekg/dns"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Exchange mocks base method.
func (m_2 *MockClient) Exchange(ctx context.Context, m *dns.Msg, network, address string) (*dns.Msg, time.Duration, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Exchange", ctx, m, network, address)
	ret0, _ := ret[0].(*dns.Msg)
	ret1, _ := ret[1].(time.Duration)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Exchange indicates an expected call of Exchange.
func (mr *MockClientMockRecorder) Exchange(ctx, m, network, address any) *MockClientExchangeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exchange", reflect.TypeOf((*MockClient)(nil).Exchange), ctx, m, network, address)
	return &MockClientExchangeCall{Call: call}
}

// MockClientExchangeCall wrap *gomock.Call
type MockClientExchangeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientExchangeCall) Return(arg0 *dns.Msg, arg1 time.Duration, arg2 error) *MockClientExchangeCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientExchangeCall) Do(f func(context.Context, *dns.Msg, string, string) (*dns.Msg, time.Duration, error)) *MockClientExchangeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientExchangeCall) DoAndReturn(f func(context.Context, *dns.Msg, string, string) (*dns.Msg, time.Duration, error)) *MockClientExchangeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
